services:
  webserver:
    image: nginx:latest
    ports:
      - 9000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
    secrets:
      - db-root-password
      - db-app-user-password
    environment:
      - ROOT_PASSWORD_FILE_PATH=/run/secrets/db-root-password
      - APP_USER_PASSWORD_FILE_PATH=/run/secrets/db-app-user-password
      - DB_HOST=db
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - BASE_URL=${BASE_URL}
      
  php:
    image: php:8.0-fpm
    build: services/php
    volumes:
      - ./app:/app
    secrets:
      - db-root-password
      - db-app-user-password
    environment:
      - ROOT_PASSWORD_FILE_PATH=/run/secrets/db-root-password
      - APP_USER_PASSWORD_FILE_PATH=/run/secrets/db-app-user-password
      - DB_HOST=db
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - BASE_URL=${BASE_URL}

  db:
    image: mysql:latest
    secrets:
      - db-root-password
      - db-app-user-password
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-root-password
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/db-app-user-password
      
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      - PMA_HOST=${PMA_HOST}

volumes:
  mysqldata:
secrets:
  db-root-password:
    file: secrets/root_password.txt
  db-app-user-password:
    file: secrets/app_user_password.txt


